# Generated by Django 4.2.1 on 2023-05-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_word_count_alter_blog_content_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', "Peut changer le titre d'un billet de blog")]},
        ),
    ]
