# Generated by Django 4.2.1 on 2023-05-29 03:39

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_alter_blog_author_blogcontributor_and_more'),
    ]

    operations = [
    ]
