# Generated by Django 4.2.1 on 2023-05-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230529_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontributor',
            old_name='contributions',
            new_name='contribution',
        ),
    ]
