# Generated by Django 4.2.1 on 2023-05-29 04:02

from django.db import migrations


def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_contributions_blogcontributor_contribution'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]

